### ISSUE TITLE
Data leak

### ISSUE THREAD

**Issue by hakonw** [singsaker/intern#10]
https://github.com/singsaker/intern/blob/54bb017f65f1ddeac34340d657e51e40dccd427f/migrations/beboer_data.json

Har disse folkene godtatt at informasjonen dems ligger offentlig ute på nettet?
Føler dette er en fil som ikke burde ha vært lastet opp

**Comment by D4ndellion** [comment]
Takk for at du sa ifra, disse filene skal nå være fjernet fra repositoriet
